name: Check dist

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: volta-cli/action@v4.0.0

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Rebuild the dist directory
        run: yarn run build

      - name: Compare the expected and actual dist directories
        run: |
          if [ "$(git diff --ignore-space-at-eol ${{inputs.dist-path}} | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after the build. See the status below:"
            git diff
            exit 1
          fi
        id: diff

      # If inners of the dist directory were different than expected, upload the expected version as an artifact
      - name: Upload artifact
        if: ${{failure() && steps.diff.conclusion == 'failure'}}
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ${{inputs.dist-path}}
