name: Lint

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: volta-cli/action@v4.0.0

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run lint
        run: yarn run lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - uses: volta-cli/action@v4.0.0

      - name: Install dependencies
        run: yarn install

      - name: Run prettier
        run: yarn run prettier -c .
