name: Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: volta-cli/action@v4.0.1

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run test
        run: yarn run test
